#!/usr/bin/env node
/* Idempotent PWA <head> injector — run from frontend/.
   Adds manifest/theme/apple meta (only if missing) plus raster icons and the
   full apple-touch-startup-image splash matrix, wrapped in PWA markers so a
   re-run replaces cleanly. */
const fs = require('fs');
const path = require('path');

const START = '<!-- PWA:START (generated by pwa/inject.js — do not edit by hand) -->';
const END = '<!-- PWA:END -->';

// device: [cssW, cssH, ratio] portrait — matches pwa/ generator
const DEVICES = [
  [375,667,2],[414,736,3],[375,812,3],[414,896,2],[414,896,3],
  [390,844,3],[360,780,3],[428,926,3],[393,852,3],[430,932,3],
  [768,1024,2],[810,1080,2],[834,1112,2],[834,1194,2],[1024,1366,2],
];

function splashLinks() {
  const out = [];
  for (const [cw, ch, r] of DEVICES) {
    const pw = cw * r, ph = ch * r;
    const base = `screen and (device-width: ${cw}px) and (device-height: ${ch}px) and (-webkit-device-pixel-ratio: ${r})`;
    out.push(`  <link rel="apple-touch-startup-image" media="${base} and (orientation: portrait)" href="pwa/splash/splash-${pw}x${ph}.png">`);
    out.push(`  <link rel="apple-touch-startup-image" media="${base} and (orientation: landscape)" href="pwa/splash/splash-${ph}x${pw}.png">`);
  }
  return out.join('\n');
}

function buildBlock(html) {
  const lines = [START];
  // Only add global tags that the page doesn't already declare, to avoid dupes.
  if (!/rel="manifest"/.test(html))                 lines.push('  <link rel="manifest" href="manifest.webmanifest">');
  if (!/name="theme-color"/.test(html))             lines.push('  <meta name="theme-color" content="#070B14">');
  if (!/apple-mobile-web-app-capable/.test(html))   lines.push('  <meta name="apple-mobile-web-app-capable" content="yes">');
  if (!/name="mobile-web-app-capable"/.test(html))  lines.push('  <meta name="mobile-web-app-capable" content="yes">');
  if (!/apple-mobile-web-app-status-bar-style/.test(html)) lines.push('  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">');
  if (!/apple-mobile-web-app-title/.test(html))     lines.push('  <meta name="apple-mobile-web-app-title" content="Niche Finder">');
  if (!/rel="apple-touch-icon"/.test(html))         lines.push('  <link rel="apple-touch-icon" href="apple-touch-icon.png">');
  // Raster icons (always in the block; harmless alongside the SVG rel=icon)
  lines.push('  <link rel="icon" type="image/png" sizes="192x192" href="icon-192.png">');
  lines.push('  <link rel="icon" type="image/png" sizes="512x512" href="icon-512.png">');
  lines.push(splashLinks());
  lines.push('  ' + END);
  return lines.join('\n');
}

const files = fs.readdirSync('.').filter(f => f.endsWith('.html'));
let changed = 0;
for (const f of files) {
  let html = fs.readFileSync(f, 'utf8');
  // strip any prior block
  html = html.replace(new RegExp(START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\n?', 'g'), '');
  if (!/<\/head>/i.test(html)) { console.log('skip (no </head>): ' + f); continue; }
  const block = buildBlock(html) + '\n';
  html = html.replace(/([ \t]*)<\/head>/i, block + '$1</head>');
  fs.writeFileSync(f, html);
  changed++;
}
console.log('injected into ' + changed + ' files');
