// Keyless provider for local development and CI. Enabled with MOCK_AI=1 or
// by requesting provider "mock" explicitly. Echoes a deterministic response
// shaped like a real one so downstream ACU metering and routing are testable.

export async function generate(req) {
  const lastUser = [...req.messages].reverse().find((m) => m.role === 'user');
  const prompt = typeof lastUser?.content === 'string' ? lastUser.content : JSON.stringify(lastUser?.content ?? '');

  const text = req.jsonSchema
    ? JSON.stringify(instantiate(req.jsonSchema))
    : `[mock] Venture analysis for: ${prompt.slice(0, 120)}`;

  return {
    provider: 'mock',
    model: 'mock-1',
    text,
    stopReason: 'end_turn',
    usage: { inputTokens: Math.ceil(prompt.length / 4), outputTokens: Math.ceil(text.length / 4) },
  };
}

// Build a minimal valid instance of a JSON schema so structured-output
// consumers can be exercised end-to-end without a real model. Arrays get
// three items so list UIs have something to render.
const SAMPLE_STRINGS = [
  'Mock Venture Opportunity Alpha',
  'MOCK SECTOR · MOCK CITY · HYBRID',
  'Deterministic placeholder generated by the gateway mock provider so the full request pipeline can be tested without API keys.',
];
function instantiate(schema, depth = 0, seed = 0) {
  if (!schema || depth > 6) return null;
  switch (schema.type) {
    case 'object': {
      const out = {};
      let i = 0;
      for (const [key, prop] of Object.entries(schema.properties || {})) {
        out[key] = instantiate(prop, depth + 1, seed + i++);
      }
      return out;
    }
    case 'array':
      return [0, 1, 2].map((i) => instantiate(schema.items, depth + 1, i));
    case 'string':
      return schema.enum ? schema.enum[0] : SAMPLE_STRINGS[seed % SAMPLE_STRINGS.length];
    case 'integer':
    case 'number':
      return 70 + ((seed * 7) % 25);
    case 'boolean':
      return true;
    default:
      return null;
  }
}
